(ns app.generator.ashari.regis
  (:require [app.generator.ashari.ips.smp_09.geografi]
            [app.generator.ashari.ips.smp_09.sosiologi]
            [app.generator.ashari.ips.smp_09.ekonomi]
            [app.generator.ashari.ips.smp_09.sejarah]
            [app.generator.ashari.geography.geo_ch_fb]
            [app.generator.ashari.geography.geo_ch_gb]
            [app.generator.ashari.geography.geo_ch_gc]
            [app.generator.ashari.assessment.geo_A]))

(def register
  [;;  {:folder "templates/piloting"
  ;;   :file   "geografi_benua-eropa.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.geografi/benua-eropa}
  ;;  {:folder "templates/piloting"
  ;;   :file   "geografi_benua-afrika.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.geografi/benua-afrika}
  ;;  {:folder "templates/piloting"
  ;;   :file   "geografi_jepang.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.geografi/jepang}
  ;;  {:folder "templates/piloting"
  ;;   :file   "coba_cakep-nggak.html"
  ;;   :topic  :other
  ;;   :gen-fn app.generator.ashari.ips.smp_09.geografi/cakep-nggak}
  ;;  {:folder "templates/piloting"
  ;;   :file   "geografi_mesir.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.geografi/mesir}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "geografi_pengertian-interaksi.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.geografi/pengertian-interaksi}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "geografi_interaksi-antarruang.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.geografi/interaksi-antarruang}
  ;;  {:folder "templates/piloting"
  ;;   :file   "geografi_sdm-australia.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.geografi/sdm-australia}
  ;;  {:folder "templates/piloting"
  ;;   :file   "geografi_ibukota-negara.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.geografi/ibukota-negara}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "geografi_potensi-sda-australia.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.geografi/potensi-sda-australia}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sosiologi_faktor-pendorong-perubahan-sosial-budaya.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sosiologi/faktor-pendorong-perubahan-sosial-budaya}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sosiologi_faktor-penghambat-perubahan-sosial-budaya.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sosiologi/faktor-penghambat-perubahan-sosial-budaya}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sosiologi_faktor-pendorong-perubahan-sosial-budaya.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sosiologi/faktor-pendorong-perubahan-sosial-budaya}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sosiologi_pengertian-globalisasi.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sosiologi/pengertian-globalisasi}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sosiologi_ciri-ciri-globalisasi.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sosiologi/ciri-ciri-globalisasi}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sosiologi_bentuk-globalisasi-budaya-dan-ekonomi.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sosiologi/bentuk-globalisasi-budaya-dan-ekonomi}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sosiologi_upaya-menghadapi-globalisasi-budaya.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sosiologi/upaya-menghadapi-globalisasi-budaya}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sosiologi_upaya-menghadapi-globalisasi-iptek.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sosiologi/upaya-menghadapi-globalisasi-iptek}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sosiologi_upaya-menghadapi-globalisasi-ekonomi.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sosiologi/upaya-menghadapi-globalisasi-ekonomi}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_faktor-produksi.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/faktor-produksi}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_persebaran-produksi-kedelai.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/persebaran-produksi-kedelai}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_pengertian-dan-tujuan-distribusi.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/pengertian-dan-tujuan-distribusi}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_distribusi-antardaerah.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/distribusi-antardaerah}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_pengertian-dan-tujuan-konsumsi.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/pengertian-dan-tujuan-konsumsi}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_ciri-benda-konsumsi.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/ciri-benda-konsumsi}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_pembagian-benda-konsumsi.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/pembagian-benda-konsumsi}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_pengertian-harga.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/pengertian-harga}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_fungsi-harga.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/fungsi-harga}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_jenis-harga.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/jenis-harga}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_pengertian-pasar.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/pengertian-pasar}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_fungsi-pasar.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/fungsi-pasar}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_jenis-pasar.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/jenis-pasar}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_perdagangan-indonesia-1.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/perdagangan-indonesia-1}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_pengertian-migrasi.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/pengertian-migrasi}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_jenis-migran-antardaerah.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/jenis-migran-antardaerah}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_pengaruh-ketergantungan-antarruang-pada-migrasi-1.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/pengaruh-ketergantungan-antarruang-pada-migrasi-1}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_pengaruh-ketergantungan-antarruang-pada-migrasi-2.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/pengaruh-ketergantungan-antarruang-pada-migrasi-2}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_pengertian-transportasi.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/pengertian-transportasi}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_transportasi-indonesia-era-kolonial.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/transportasi-indonesia-era-kolonial}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_transportasi-indonesia-era-orde-lama.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/transportasi-indonesia-era-orde-lama}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_transportasi-indonesia-era-orde-baru.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/transportasi-indonesia-era-orde-baru}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_pendidikan-di-indonesia-1.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/pendidikan-di-indonesia-1}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_pendidikan-di-indonesia-2.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/pendidikan-di-indonesia-2}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sosiologi_hakikat-perubahan-sosial-budaya-2.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sosiologi/hakikat-perubahan-sosial-budaya-2}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sosiologi_karakteristik-perubahan-sosial-budaya-2.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sosiologi/karakteristik-perubahan-sosial-budaya-2}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sosiologi_bentuk-perubahan-sosial-budaya-dari-waktu.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sosiologi/bentuk-perubahan-sosial-budaya-dari-waktu}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sosiologi_bentuk-perubahan-sosial-budaya-dari-pengaruh.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sosiologi/bentuk-perubahan-sosial-budaya-dari-pengaruh}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sosiologi_bentuk-perubahan-sosial-budaya-dari-perencanaan.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sosiologi/bentuk-perubahan-sosial-budaya-dari-perencanaan}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sosiologi_faktor-penyebab-perubahan-sosial-budaya-2.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sosiologi/faktor-penyebab-perubahan-sosial-budaya-2}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sosiologi_faktor-pendorong-perubahan-sosial-budaya-2.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sosiologi/faktor-pendorong-perubahan-sosial-budaya-2}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sosiologi_faktor-penghambat-perubahan-sosial-budaya-2.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sosiologi/faktor-penghambat-perubahan-sosial-budaya-2}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sosiologi_ciri-ciri-globalisasi-2.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sosiologi/ciri-ciri-globalisasi-2}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sosiologi_bentuk-globalisasi-budaya.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sosiologi/bentuk-globalisasi-budaya}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_pendidikan-di-dunia-1.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/pendidikan-di-dunia-1}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_pendidikan-di-dunia-2.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/pendidikan-di-dunia-2}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_pendidikan-di-dunia-3.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/pendidikan-di-dunia-3}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_pengaruh-ketergantungan-antarruang-pada-pendidikan.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/pengaruh-ketergantungan-antarruang-pada-pendidikan}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_pengertian-lembaga-ekonomi.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/pengertian-lembaga-ekonomi}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_lembaga-ekonomi-di-indonesia-1.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/lembaga-ekonomi-di-indonesia-1}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_lembaga-ekonomi-di-indonesia-2.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/lembaga-ekonomi-di-indonesia-2}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_lembaga-ekonomi-di-indonesia-3.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/lembaga-ekonomi-di-indonesia-3}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_lembaga-ekonomi-di-indonesia-4.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/lembaga-ekonomi-di-indonesia-4}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_manfaat-pengembangan-pusat-keunggulan-ekonomi.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/manfaat-pengembangan-pusat-keunggulan-ekonomi}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_masyarakat-ekonomi-asean-1.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/masyarakat-ekonomi-asean-1}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_masyarakat-ekonomi-asean-2.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/masyarakat-ekonomi-asean-2}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_kelangkaan-sebagai-permasalahan-ekonomi-1.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/kelangkaan-sebagai-permasalahan-ekonomi-1}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_kelangkaan-sebagai-permasalahan-ekonomi-2.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/kelangkaan-sebagai-permasalahan-ekonomi-2}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_faktor-yang-mempengaruhi-kebutuhan-manusia-1.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/faktor-yang-mempengaruhi-kebutuhan-manusia-1}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_faktor-yang-mempengaruhi-kebutuhan-manusia-2.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/faktor-yang-mempengaruhi-kebutuhan-manusia-2}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_asean-free-trade-area.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/asean-free-trade-area}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_asia-pacific-economic-cooperation.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/asia-pacific-economic-cooperation}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "ekonomi_european-union.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.ekonomi/european-union}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sejarah_masa-praaksara-7.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sejarah/masa-praaksara-7}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "geografi_benua-asia-2.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.geografi/benua-asia-2}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "geografi_benua-amerika-2.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.geografi/benua-amerika-2}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "geografi_benua-eropa-2.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.geografi/benua-eropa-2}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "geografi_benua-afrika-2.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.geografi/benua-afrika-2}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "geografi_benua-australia-2.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.geografi/benua-australia-2}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "geografi_jepang-2.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.geografi/jepang-2}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "geografi_tiongkok-2.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.geografi/tiongkok-2}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "geografi_amerika-serikat-2.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.geografi/amerika-serikat-2}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "geografi_brasil-2.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.geografi/brasil-2}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sejarah_masa-praaksara-6.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sejarah/masa-praaksara-6}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sejarah_masa-praaksara-10.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sejarah/masa-praaksara-10}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sejarah_masa-praaksara-7b.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sejarah/masa-praaksara-7b}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sejarah_masa-praaksara.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sejarah/masa-praaksara}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sejarah_masa-praaksara-8.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sejarah/masa-praaksara-8}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sejarah_masa-praaksara-9.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sejarah/masa-praaksara-9}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sejarah_masa-praaksara-4.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sejarah/masa-praaksara-4}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sejarah_masa-praaksara-3.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sejarah/masa-praaksara-3}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sejarah_masa-praaksara-6b.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sejarah/masa-praaksara-6b}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sejarah_masa-praaksara-5.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sejarah/masa-praaksara-5}
  ;;  {:folder "templates/ips/smp_09"
  ;;   :file   "sejarah_masa-praaksara-8b.html"
  ;;   :topic  :smp-ips
  ;;   :gen-fn app.generator.ashari.ips.smp_09.sejarah/masa-praaksara-8b}
  ;;  {:folder "templates/geography/UTBK_F"
  ;;   :file   "geo_FB_proyeksi-peta-1a.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.geography.geo_ch_fb/proyeksi-peta-1a}
  ;;  {:folder "templates/geography/UTBK_F"
  ;;   :file   "geo_FB_proyeksi-peta-3a.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.geography.geo_ch_fb/proyeksi-peta-3a}
  ;;  {:folder "templates/geography/UTBK_F"
  ;;   :file   "geo_FB_proyeksi-peta-3b.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.geography.geo_ch_fb/proyeksi-peta-3b}
  ;;  {:folder "templates/geography/UTBK_F"
  ;;   :file   "geo_FB_proyeksi-peta-3c.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.geography.geo_ch_fb/proyeksi-peta-3c}
  ;;  {:folder "templates/geography/UTBK_F"
  ;;   :file   "geo_FB_proyeksi-peta-3d.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.geography.geo_ch_fb/proyeksi-peta-3d}
  ;;  {:folder "templates/geography/UTBK_F"
  ;;   :file   "geo_FB_proyeksi-peta-3e.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.geography.geo_ch_fb/proyeksi-peta-3e}
  ;;  {:folder "templates/geography/UTBK_F"
  ;;   :file   "geo_FB_proyeksi-peta-5a.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.geography.geo_ch_fb/proyeksi-peta-5a}
  ;;  {:folder "templates/geography/UTBK_F"
  ;;   :file   "geo_FB_proyeksi-peta-6a.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.geography.geo_ch_fb/proyeksi-peta-6a}
  ;;  {:folder "templates/geography/UTBK_G"
  ;;   :file   "geo_GB_memahami-konsep-citra-nonfoto-1a.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.geography.geo_ch_gb/memahami-konsep-citra-nonfoto-1a}
  ;;  {:folder "templates/geography/UTBK_G"
  ;;   :file   "geo_GC_langkah-interpretasi-citra-1a.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.geography.geo_ch_gc/langkah-interpretasi-citra-1a}
  ;;  {:folder "templates/geography/UTBK_F"
  ;;   :file   "geo_FB_proyeksi-peta-7.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.geography.geo_ch_fb/proyeksi-peta-7} 
  ;;  {:folder "templates/assessment/sma_10"
  ;;   :file   "geo_AA_pentingnya-berpikir-spasial.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/pentingnya-berpikir-spasial}
  ;;  {:folder "templates/assessment/sma_10"
  ;;   :file   "geo_AB_mengapa-perlu-belajar-geografi.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/mengapa-perlu-belajar-geografi}
  ;;  {:folder "templates/assessment/sma_10"
  ;;   :file   "geo_AC_ruang-lingkup-geografi-1.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/ruang-lingkup-geografi-1}
  ;;  {:folder "templates/assessment/sma_10"
  ;;   :file   "geo_AC_aspek-geografi-1.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/aspek-geografi-1}
  ;;  {:folder "templates/assessment/sma_10"
  ;;   :file   "geo_AC_objek-material-geografi-1.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/objek-material-geografi-1}
  ;;  {:folder "templates/assessment/sma_10"
  ;;   :file   "geo_AC_objek-material-geografi-2.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/objek-material-geografi-2}
  ;;  {:folder "templates/assessment/sma_10"
  ;;   :file   "geo_AC_objek-material-geografi-3.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/objek-material-geografi-3}
  ;;  {:folder "templates/assessment/sma_10"
  ;;   :file   "geo_AC_aspek-geografi-2.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/aspek-geografi-2}
  ;;  {:folder "templates/assessment/sma_10"
  ;;   :file   "geo_AD_konsep-geografi-bagian-1.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/konsep-geografi-bagian-1}
  ;;  {:folder "templates/assessment/sma_10"
  ;;   :file   "geo_AD_pendekatan-geografi-1.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/pendekatan-geografi-1}
  ;;  {:folder "templates/assessment/sma_10"
  ;;   :file   "geo_AD_pendekatan-geografi-2.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/pendekatan-geografi-2}
  ;;  {:folder "templates/assessment/sma_10"
  ;;   :file   "geo_AD_konsep-geografi-bagian-2.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/konsep-geografi-bagian-2}
  ;;  {:folder "templates/assessment/sma_10"
  ;;   :file   "geo_AE_komponen-peta-bagian-3-i.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/komponen-peta-bagian-3-i}
  ;;  {:folder "templates/assessment/sma_10"
  ;;   :file   "geo_AE_jenis-jenis-peta.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/jenis-jenis-peta} 
  ;;  {:folder "templates/assessment/sma_10" 
  ;;   :file   "geo_AF_generalisasi-dan-eksagerasi-peta.html" 
  ;;   :topic  :geo 
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/generalisasi-dan-eksagerasi-peta}
  ;;  {:folder "templates/assessment/sma_10"
  ;;   :file   "geo_AG_apa-itu-peta-kontur.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/apa-itu-peta-kontur}
  ;;  {:folder "templates/assessment/sma_10"
  ;;   :file   "geo_AG_menghitung-interval-kontur-pada-peta-kontur.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/menghitung-interval-kontur-pada-peta-kontur}
  ;;  {:folder "templates/assessment/sma_10"
  ;;   :file   "geo_AH_macam-citra-foto-berdasarkan-spektrum.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/macam-citra-foto-berdasarkan-spektrum} 
  ;;  {:folder "templates/assessment/sma_10" 
  ;;   :file   "geo_AH_macam-citra-foto-berdasarkan-jenis-kamera-dan-warna-yang-dihasilkan.html" 
  ;;   :topic  :geo 
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/macam-citra-foto-berdasarkan-jenis-kamera-dan-warna-yang-dihasilkan}
  ;;  {:folder "templates/assessment/sma_10"
  ;;   :file   "geo_AH_memahami-konsep-citra-nonfoto-1.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/memahami-konsep-citra-nonfoto-1}
  ;;  {:folder "templates/assessment/sma_10"
  ;;   :file   "geo_AH_memahami-konsep-citra-nonfoto-2.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/memahami-konsep-citra-nonfoto-2}
  ;;  {:folder "templates/assessment/sma_10"
  ;;   :file   "geo_AI_apa-itu-interpretasi-citra.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/apa-itu-interpretasi-citra}
  ;;  {:folder "templates/assessment/sma_10"
  ;;   :file   "geo_AI_unsur-interpretasi-citra-bagian-1-2.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/unsur-interpretasi-citra-bagian-1-2}
  ;;  {:folder "templates/assessment/sma_10"
  ;;   :file   "geo_AI_unsur-interpretasi-citra-bagian-1-1.html"
  ;;   :topic  :geo
  ;;   :gen-fn app.generator.ashari.assessment.geo_A/unsur-interpretasi-citra-bagian-1-1}
   {:folder "templates/assessment/sma_10"
    :file   "geo_AI_unsur-interpretasi-citra-bagian-3-1.html"
    :topic  :geo
    :gen-fn app.generator.ashari.assessment.geo_A/unsur-interpretasi-citra-bagian-3-1}
   {:folder "templates/assessment/sma_10"
    :file   "geo_AI_contoh-interpretasi-citra-berdasarkan-unsur.html"
    :topic  :geo
    :gen-fn app.generator.ashari.assessment.geo_A/contoh-interpretasi-citra-berdasarkan-unsur}
   {:folder "templates/assessment/sma_10"
    :file   "geo_AI_langkah-interpretasi-citra-1.html"
    :topic  :geo
    :gen-fn app.generator.ashari.assessment.geo_A/langkah-interpretasi-citra-1}
   {:folder "templates/assessment/sma_10"
    :file   "geo_AI_langkah-interpretasi-citra-2.html"
    :topic  :geo
    :gen-fn app.generator.ashari.assessment.geo_A/langkah-interpretasi-citra-2}
   {:folder "templates/assessment/sma_10"
    :file   "geo_AI_penentuan-skala-foto-udara.html"
    :topic  :geo
    :gen-fn app.generator.ashari.assessment.geo_A/penentuan-skala-foto-udara}
   {:folder "templates/assessment/sma_10"
    :file   "geo_AI_meninjau-ulang-keterampilan-pengindraan-jauh.html"
    :topic  :geo
    :gen-fn app.generator.ashari.assessment.geo_A/meninjau-ulang-keterampilan-pengindraan-jauh}])