(ns app.generator.sbd.regis
  (:require [app.generator.sbd.arit]
            [app.generator.sbd.logic]
            [app.generator.sbd.grammar]
            [app.generator.sbd.jabar]
            [app.generator.sbd.mcore]
            [app.generator.sbd.vocab]
            [app.generator.sbd.geo]))

(comment
  [{:folder "sbd"
    :file   "arit-01.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-01}
   {:folder "sbd"
    :file   "arit-02.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-02}
   {:folder "sbd"
    :file   "arit-03.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-03}
   {:folder "sbd"
    :file   "arit-04.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-04}
   {:folder "sbd"
    :file   "arit-05.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-05}
   {:folder "sbd"
    :file   "arit-06.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-06}
   {:folder "sbd"
    :file   "arit-07.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-07}
   {:folder "sbd"
    :file   "arit-08.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-08}
   {:folder "sbd"
    :file   "arit-09.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-09}
   {:folder "sbd"
    :file   "arit-10.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-10}
   {:folder "sbd"
    :file   "arit-11.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-11}
   {:folder "sbd"
    :file   "arit-12.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-12}
   {:folder "sbd"
    :file   "arit-13.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-13}
   {:folder "sbd"
    :file   "arit-14.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-14}
   {:folder "sbd"
    :file   "arit-15.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-15}
   {:folder "sbd"
    :file   "arit-16.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-16}
   {:folder "sbd"
    :file   "arit-19.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-19}
   {:folder "sbd"
    :file   "arit-21.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-21}
   {:folder "sbd"
    :file   "arit-22.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-22}
   {:folder "sbd"
    :file   "arit-23.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-23}
   {:folder "sbd"
    :file   "jabar-01.html"
    :topic  :math
    :gen-fn app.generator.sbd.jabar/jabar-01}
   {:folder "sbd"
    :file   "jabar-02.html"
    :topic  :math
    :gen-fn app.generator.sbd.jabar/jabar-02}
   {:folder "sbd"
    :file   "jabar-03.html"
    :topic  :math
    :gen-fn app.generator.sbd.jabar/jabar-03}
   {:folder "sbd"
    :file   "logic-01.html"
    :topic  :logic
    :gen-fn app.generator.sbd.logic/logic-01}
   {:folder "sbd"
    :file   "logic-02.html"
    :topic  :logic
    :gen-fn app.generator.sbd.logic/logic-02}
   {:folder "sbd"
    :file   "logic-03.html"
    :topic  :logic
    :gen-fn app.generator.sbd.logic/logic-03}
   {:folder "sbd"
    :file   "logic-04.html"
    :topic  :logic
    :gen-fn app.generator.sbd.logic/logic-04}
   {:folder "sbd"
    :file   "logic-05.html"
    :topic  :logic
    :gen-fn app.generator.sbd.logic/logic-05}
   {:folder "sbd"
    :file   "logic-06.html"
    :topic  :logic
    :gen-fn app.generator.sbd.logic/logic-06}
   {:folder "sbd"
    :file   "logic-07.html"
    :topic  :logic
    :gen-fn app.generator.sbd.logic/logic-07}
   {:folder "sbd"
    :file   "grammar-01.html"
    :topic  :english
    :gen-fn app.generator.sbd.grammar/grammar-01}
   {:folder "sbd"
    :file   "grammar-02.html"
    :topic  :english
    :gen-fn app.generator.sbd.grammar/grammar-02}
   {:folder "sbd"
    :file   "grammar-03.html"
    :topic  :english
    :gen-fn app.generator.sbd.grammar/grammar-03}
   {:folder "sbd"
    :file   "grammar-04.html"
    :topic  :english
    :gen-fn app.generator.sbd.grammar/grammar-04}
   {:folder "sbd"
    :file   "grammar-05.html"
    :topic  :english
    :gen-fn app.generator.sbd.grammar/grammar-05}
   {:folder "sbd"
    :file   "grammar-06.html"
    :topic  :english
    :gen-fn app.generator.sbd.grammar/grammar-06}
   {:folder "sbd"
    :file   "grammar-07.html"
    :topic  :english
    :gen-fn app.generator.sbd.grammar/grammar-07}
   {:folder "sbd"
    :file   "grammar-08.html"
    :topic  :english
    :gen-fn app.generator.sbd.grammar/grammar-08}
   {:folder "sbd"
    :file   "grammar-09.html"
    :topic  :english
    :gen-fn app.generator.sbd.grammar/grammar-09}
   {:folder "sbd"
    :file   "grammar-10.html"
    :topic  :english
    :gen-fn app.generator.sbd.grammar/grammar-10}
   {:folder "sbd"
    :file   "grammar-11.html"
    :topic  :english
    :gen-fn app.generator.sbd.grammar/grammar-11}
   {:folder "sbd"
    :file   "grammar-12.html"
    :topic  :english
    :gen-fn app.generator.sbd.grammar/grammar-12}
   {:folder "sbd"
    :file   "grammar-13.html"
    :topic  :english
    :gen-fn app.generator.sbd.grammar/grammar-13}
   {:folder "sbd"
    :file   "grammar-14.html"
    :topic  :english
    :gen-fn app.generator.sbd.grammar/grammar-14}
   {:folder "sbd"
    :file   "grammar-15.html"
    :topic  :english
    :gen-fn app.generator.sbd.grammar/grammar-15}

   {:folder "sbd"
    :file   "jabar-05.html"
    :topic  :math
    :gen-fn app.generator.sbd.jabar/jabar-05}
   {:folder "sbd"
    :file   "jabar-06.html"
    :topic  :math
    :gen-fn app.generator.sbd.jabar/jabar-06}
   {:folder "sbd"
    :file   "mcore-01.html"
    :topic  :math
    :gen-fn app.generator.sbd.mcore/mcore-01}
   {:folder "sbd"
    :file   "arit-24.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-24}
   {:folder "sbd"
    :file   "jabar-05.html"
    :topic  :math
    :gen-fn app.generator.sbd.jabar/jabar-05}
   {:folder "sbd"
    :file   "arit-17.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-17}
   {:folder "sbd"
    :file   "arit-18.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-18}
   {:folder "sbd"
    :file   "mcore-02.html"
    :topic  :math
    :gen-fn app.generator.sbd.mcore/mcore-02}
   {:folder "sbd"
    :file   "mcore-03.html"
    :topic  :math
    :gen-fn app.generator.sbd.mcore/mcore-03}
   {:folder "sbd"
    :file   "mcore-04.html"
    :topic  :math
    :gen-fn app.generator.sbd.mcore/mcore-04}
   {:folder "sbd"
    :file   "mcore-05.html"
    :topic  :math
    :gen-fn app.generator.sbd.mcore/mcore-05}
   {:folder "sbd"
    :file   "mcore-06.html"
    :topic  :math
    :gen-fn app.generator.sbd.mcore/mcore-06}
   {:folder "sbd"
    :file   "jabar-03.html"
    :topic  :math
    :gen-fn app.generator.sbd.jabar/jabar-03}
   {:folder "sbd"
    :file   "jabar-04.html"
    :topic  :math
    :gen-fn app.generator.sbd.jabar/jabar-04}
   {:folder "sbd"
    :file   "arit-20.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-20}
   {:folder "sbd"
    :file   "geo-01.html"
    :topic  :math
    :gen-fn app.generator.sbd.geo/geo-01}
   {:folder "sbd" :file   "grammar-16.html" :topic  :english
    :gen-fn app.generator.sbd.grammar/grammar-16}
   {:folder "sbd" :file   "grammar-17.html" :topic  :english
    :gen-fn app.generator.sbd.grammar/grammar-17}
   {:folder "sbd" :file   "grammar-18.html" :topic  :english
    :gen-fn app.generator.sbd.grammar/grammar-18}
   {:folder "sbd" :file   "vocab-01.html" :topic  :english
    :gen-fn app.generator.sbd.vocab/vocab-01}
   {:folder "sbd", :file "vocab-02.html", :topic :english,
    :gen-fn app.generator.sbd.vocab/vocab-02}
   {:folder "sbd", :file "vocab-03.html", :topic :english,
    :gen-fn app.generator.sbd.vocab/vocab-03}
   {:folder "sbd", :file "vocab-04.html", :topic :english,
    :gen-fn app.generator.sbd.vocab/vocab-04}
   {:folder "sbd", :file "vocab-05.html", :topic :english,
    :gen-fn app.generator.sbd.vocab/vocab-05}
   {:folder "sbd" :file   "grammar-19.html" :topic  :english
    :gen-fn app.generator.sbd.grammar/grammar-19}
   {:folder "sbd" :file   "grammar-20.html" :topic  :english
    :gen-fn app.generator.sbd.grammar/grammar-20}
   {:folder "math-geo"
    :file   "geo-01.html"
    :topic  :math
    :gen-fn app.generator.sbd.geo/geo-01}
   {:folder "math-arit"
    :file   "arit-25.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-25}
   {:folder "math-arit"
    :file   "arit-26.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-26}
   {:folder "math-arit"
    :file   "arit-27.html"
    :topic  :math
    :gen-fn app.generator.sbd.arit/arit-27}
   {:folder "math-jabar"
    :file   "jabar-07.html"
    :topic  :math
    :gen-fn app.generator.sbd.jabar/jabar-07}])

(def register
  [])
